[POST] Google I/O - Inteligência Artificial
elo7/tech-blog pull request #84
Opened 2017-06-02 02:27 UTC by FernandaBernardo

@davidrobert

2017-06-04 16:43 UTC, abarbosa94 commented on src/posts/google-io.html.md
> +Um dos grandes lançamentos foi a segunda geração do **Tensor Processing Units (TPU)**. Um processador projetado especificamente para aprendizado de máquina utilizado principalmente no produto Tensor
é TensorFlow, tudo junto mesmo :)

2017-06-04 16:44 UTC, abarbosa94 commented on src/posts/google-io.html.md
> +- [https://blog.google/topics/google-cloud/google-cloud-offer-tpus-machine-learning/](https://blog.google/topics/google-cloud/google-cloud-offer-tpus-machine-learning/)
Não seria legal deixar esse link como acesso ao negrito do TPU? Tipo, ficaria algo como 

[(TPU)](https://blog.google/topics/google-cloud/google-cloud-offer-tpus-machine-learning/), logo no parágrafo anterior.

2017-06-04 16:45 UTC, abarbosa94 commented on src/posts/google-io.html.md
> +A versão 2 do **Google Home** foi apresentada. As principais novos recursos:
Não seria Os principais novos recursos?

2017-06-04 23:23 UTC, mikedias commented on src/posts/google-io.html.md
> +- [https://blog.google/products/assistant/your-assistant-getting-better-on-google-home-and-your-phone/](https://blog.google/products/assistant/your-assistant-getting-better-on-google-home-and-your-ph
Coloca este link no **Google Assistent** do parágrafo anterior

2017-06-04 23:25 UTC, mikedias commented on src/posts/google-io.html.md
> +- [https://developer.android.com/topic/performance/vitals/index.html](https://developer.android.com/topic/performance/vitals/index.html)
Coloca esse link na palavra Vitals do parágrafo anterior.

2017-06-04 23:26 UTC, mikedias commented on src/posts/google-io.html.md
> +O suporte a novas linguagens de programação foi incorporado ao Tensor Flow. Suportando agora Haskell, C++, Java, Python, Go, etc.
TensorFlow tudo junto

2017-06-05 12:38 UTC, ericvinicius commented on src/posts/google-io.html.md
> +Um dos grandes lançamentos foi a segunda geração do **Tensor Processing Units (TPU)**. Um processador projetado especificamente para aprendizado de máquina utilizado principalmente no produto Tensor
Acho que podia ter a explicação do que é teraFlops, ou pelo menos um link.

2017-06-05 12:57 UTC, ericvinicius commented on src/posts/google-io.html.md
> +No geral o Google I/O 2017 foi bem denso em conteúdo. Ocorreram 155 sessões, 100 office hours, 85 code labs e 19 sandboxes!
Esse trecho me parece um conclusão. Deveria ficar aqui mesmo?

2017-06-05 14:09 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +description: Inteligência artificial foi um dos grandes temas do Google I/O. Todos os produtos da Google estão utilizando algum tipo de camada de inteligência artificial agora e vão usar cada vez mai
"...algum tipo de camada de inteligência artificial" não ficaria melhor com "alguma camada de inteligência artificial"? Tem o mesmo efeito semântico mas não repete o "de".

Eu tiraria esse "agora" desse trecho no final, me parece um pouco deslocado aqui. Acho que isso poderia ser reforçado começando o trecho com a palavra "Atualmente", talvez ("Atualmente, todos os produtos..."), e removendo o "agora" aqui. Também seria bom incluir uma vírgula antes do "e", pra marcar uma pausa no texto.

@tiagolimaelo7

2017-06-05 14:34 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +***Inteligência artificial*** foi um dos grandes temas da conferência. Todos os produtos da Google estão utilizando algum tipo de camada de inteligência artificial agora e vão usar cada vez mais no f
Mesmos comentários acima.

@tiagolimaelo7

2017-06-05 14:38 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Um dos grandes lançamentos foi a segunda geração do **Tensor Processing Units (TPU)**. Um processador projetado especificamente para aprendizado de máquina utilizado principalmente no produto Tensor
Incluir uma vírgula aqui: "...para aprendizado de máquina, utilizado principalmente..." (oração subordinada explicativa)

Incluir uma vírgula aqui: "Com esse novo parque de equipamentos, a Google espera..." (oração subordinada adverbial)

@tiagolimaelo7

2017-06-05 14:40 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +A Google está efetivamente transformando sua plataforma de computação em nuvem para dar total suporte a Inteligência Artificial.
Uso de crase em "total suporte à Inteligência Artificial" (preposição + artigo).

@tiagolimaelo7

2017-06-05 14:51 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O **Google Assistent** teve melhorias significativas. O Google Assistent começou no celular Pixel mas agora já está em mais de 100 milhões de dispositivos Android. A nova versão do assistente agora p
Nesse trecho "O Google Assistent começou no celular Pixel **mas** agora já está em mais de 100 milhões de dispositivos Android", eu sugiro mudar o "mas" por "e", porque "mas" é conjunção adversativa (idéia de oposição entre as orações, o que é não é o caso). Eu removeria o "agora" por redundância, o "já está" me parece suficiente pra passar a idéia de "atualmente".

"...conteúdo relevante em sua tela" não seria melhor com "...conteúdo relevante na tela do dispositivo"? É que "em sua tela" parece se dirigir ao leitor, e nenhum outro trecho traz essa idéia.

@tiagolimaelo7

2017-06-05 14:53 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +- Agora é possível pode digitar sua consulta em vez de dizê-lo em voz alta;
"Agora é possível pode digitar" -> "Agora é possível digitar". Novamente aqui pessoalmente acho melhor se referir a "a consulta" ou "uma consulta", ao invés de "sua consulta"

@tiagolimaelo7

2017-06-05 15:01 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +- O Google Assistent está sendo lançado também para a plataforma iOS (uma alternativa ao Siri);
Dado o contexto do post, esse uso do gerúndio no "está sendo" me pareceu um pouco estranho, a construção indica o tempo presente mas é isso mesmo? Ou seria "será lançado" (futuro) ou "foi lançado" (passado)? Se a idéia de tempo for o presente tudo bem.

@tiagolimaelo7

2017-06-05 15:01 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +- É possível usar o Google Assistent para enviar dinheiro para outras pessoa (inclusive dentro de um chat);
"É possível" ou "Será possível"?

@tiagolimaelo7

2017-06-05 15:02 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +A versão 2 do **Google Home** foi apresentada. As principais novos recursos:
"Os principais novos recursos"

@tiagolimaelo7

2017-06-05 15:03 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +- Respostas visuais integração com smart TVs ou **Chromecast**. Exemplos: "OK Google, mostre o meu calendário para hoje" e o Google Home pode exibir instantaneamente os eventos do seu dia em uma TV c
"Respostas visuais na integração"?

@tiagolimaelo7

2017-06-05 19:53 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O Google Photos recebeu uma série de novos recursos. Incluindo melhor compartilhamento de álbuns com pessoas que aparecem nas fotos (utilizando reconhecimento facial) e no futuro irá permitir a remoç
A pontuação/vírgulas/conectivos nesse parágrafo está um pouco confusa. Acho que poderia ser refatorado para algo assim:

"O Google Photos recebeu uma série de novos recursos, incluindo melhorias no compartilhamento de álbuns com pessoas que aparecem nas fotos, utilizando reconhecimento facial. No futuro, será permitido a remoção de itens indesejados das fotos como, por exemplo, um objeto que atrapalhe a imagem de alguma pessoa ao fundo. Também foi lançado uma feature para impressão de fotos."

@tiagolimaelo7

2017-06-05 19:56 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O lançamento da versão beta do **Android O** ocorreu durante o evento. Foi revelado que a contagem de dispositivos ativos do Android ultrapassa 2 bilhões mensais. A nova versão do Android tem as prin
"...dispositivos ativos do Android ultrapassa 2 bilhões mensais". Faz sentido esse "mensais" aqui? A príncipio essa expressão seria um sinônimo de "2 bilhões por mês", o que soa esquisito.

Acho que o início do segundo trecho poderia ser um pouco alterado:

"A nova versão do Android tem como principais características o foco em segurança..."

@tiagolimaelo7

2017-06-05 20:01 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Mirando no próximo bilhão usuários on-line para a plataforma está sendo desenvolvida a versão Android Go. Que tem como objetivo conseguir funcionar em celulares com poucos recursos e deverá ser lança
Incluir uma vírgula após "para a plataforma".

O segundo trecho inicia com "Que tem como..." se referindo à oração anterior que na verdade já terminou. Faria sentido se fosse usada uma vírgula, mas acho melhor o "ponto na mesma linha como está", então sugiro mudar o "Que tem como objetivo..." para "Esse produto tem como objetivo...". Também poderia ser "Essa versão" mas aí essa palavra teria que sair da oração anterior:

"...está sendo desenvolvido o Android Go. Essa versão tem como objetivo..."

"conseguir funcionar" -> acho que apenas "funcionar" é melhor.

@tiagolimaelo7

2017-06-05 20:03 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +No geral o Google I/O 2017 foi bem denso em conteúdo. Ocorreram 155 sessões, 100 office hours, 85 code labs e 19 sandboxes!
Esse trecho ("No geral o Google I/O...") me parece mais uma introdução, na verdade. Não poderia estar lá no topo? Ainda mais porque haverá uma série de posts. De qualquer modo ele parece meio fora do lugar aqui.

@tiagolimaelo7

2017-06-05 20:13 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Em 2016 a Google adquiriu a [Api.ai](https://api.ai) uma plataforma de conversação, que facilita a criação de bots, incluindo compreensão de linguagem natural em diversos idiomas, aprendizado de máqu
Incluir uma vírgula após o "Api.ai" (antes de "uma plataforma de...") e remover a vírgula após "conversação".

Trocar a vírgula em "linguagem natural em diversos idiomas, aprendizado de máquina" por "e" ("linguagem natural em diversos idiomas e aprendizado de máquina").

Eu incluiria uma vírgula após "A plataforma evoluiu" apenas para melhorar a fluência do texto. 

Onde diz "...um SDK bem evoluído..." talvez pudéssemos trocar a palavra "evoluído" aqui? É que ela foi usada antes e repetir palavras em um trecho próximo não é muito bom pra leitura 😄....talvez "um SDK bem maduro" seja melhor? 

No final: "...que facilita a integração" ou "...para facilitar a integração"

@tiagolimaelo7

2017-06-05 20:14 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O foco no Tensor Flow esta bastante elevado:
"está" com acento.

@tiagolimaelo7

2017-06-05 20:15 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O suporte a novas linguagens de programação foi incorporado ao Tensor Flow. Suportando agora Haskell, C++, Java, Python, Go, etc.
Vírgula ao invés de "ponto na mesma linha" ficaria melhor aqui, após "...ao TensorFlow"

@tiagolimaelo7

2017-06-05 20:15 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Durante o evento foi anunciado o **TensorFlow Lite** uma versão do TensorFlow para mobile.
Incluir uma vírgula após o "TensorFlow Lite"

@tiagolimaelo7

2017-06-05 20:20 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Durante as sessões foi apresentado a Cloud de TPUs. Aparentemente bem poderosa, mas ainda na versão Alpha. A cloud pode se integrar com um conjunto de clusters heterogêneos, e diversas otimizações de
Vírgula ao invés de "ponto na mesma linha" ficaria melhor aqui, após "...na versão Alpha"

@tiagolimaelo7

2017-06-07 14:02 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +description: Inteligência artificial foi um dos grandes temas do Google I/O. Atualmente, todos os produtos da Google estão utilizando algum tipo de camada de inteligência artificial e vão usar cada v
"...algum tipo de camada de inteligência artificial" não ficaria melhor com "alguma camada de inteligência artificial"? Tem o mesmo efeito semântico mas não repete o "de".

Também seria bom incluir uma vírgula antes do "e", pra marcar uma pausa no texto (mas a vírgula aqui é opcional).

@tiagolimaelo7

2017-06-07 14:02 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +***Inteligência artificial*** foi um dos grandes temas da conferência. Atualmente, todos os produtos da Google estão utilizando algum tipo de camada de inteligência artificial e vão usar cada vez mai
Mesmos comentários mais acima.

@tiagolimaelo7

2017-06-07 14:11 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +No geral o Google I/O 2017 foi bem denso em conteúdo. Ocorreram 155 sessões, 100 office hours, 85 code labs e 19 sandboxes!
Acho que seria melhor que esse parágrafo iniciasse o texto, para contextualizar o leitor (prosseguindo com o parágrafo que está acima, "Inteligência artificial foi um dos grandes temas...")

@tiagolimaelo7

2017-06-07 14:24 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Um dos grandes lançamentos foi a segunda geração do **Tensor Processing Units (TPU)**. Um processador projetado especificamente para aprendizado de máquina utilizado principalmente no produto TensorF
Acho que vírgula ao invés de "ponto na mesma linha" seria melhor, antes de "Um processador projetado..." (até por ser um trecho subordinado ao primeiro)

Incluir uma vírgula: "...para aprendizado de máquina, utilizado principalmente..." (oração subordinada explicativa)

Incluir uma vírgula aqui: "Com esse novo parque de equipamentos, a Google espera..." (oração subordinada adverbial)

@tiagolimaelo7

2017-06-07 14:25 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +A Google está efetivamente transformando sua plataforma de computação em nuvem para dar total suporte a Inteligência Artificial.
Uso de crase em "total suporte à Inteligência Artificial" (preposição + artigo).

@tiagolimaelo7

2017-06-07 14:34 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O **Google Assistent** teve melhorias significativas. O Google Assistent começou no celular Pixel e agora já está em mais de 100 milhões de dispositivos Android. A nova versão do assistente agora pod
No trecho "...começou no celular Pixel e agora já está...", eu removeria o "agora" por redundância, o "já está" me parece suficiente pra passar a idéia de "atualmente".

@tiagolimaelo7

2017-06-07 14:35 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +- Agora é possível pode digitar uma consulta em vez de dizê-lo em voz alta;
"...em vez de dizê-lo em voz alta" -> "dizê-la", já que se refere à palavra "consulta", feminina.

@tiagolimaelo7

2017-06-07 14:36 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +A versão 2 do **Google Home** foi apresentada. Os principais novos recursos:
Talvez "Os principais novos recursos são:"?

@tiagolimaelo7

2017-06-07 14:41 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O Google Photos recebeu uma série de novos recursos. Incluindo melhor compartilhamento de álbuns com pessoas que aparecem nas fotos (utilizando reconhecimento facial) e no futuro irá permitir a remoç
A pontuação/vírgulas/conectivos nesse parágrafo está um pouco confusa. Acho que poderia ser refatorado para algo assim (alterando pontuação/vírgulas/conectivos e mantendo as mesmas palavras):

"O Google Photos recebeu uma série de novos recursos, incluindo melhorias no compartilhamento de álbuns com pessoas que aparecem nas fotos, utilizando reconhecimento facial. No futuro, será permitido a remoção de itens indesejados das fotos como, por exemplo, um objeto que atrapalhe a imagem de alguma pessoa ao fundo. Também foi lançada uma feature para impressão de fotos."

@tiagolimaelo7

2017-06-07 14:41 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O lançamento da versão beta do **Android O** ocorreu durante o evento. Foi revelado que a contagem de dispositivos ativos do Android ultrapassa 2 bilhões mensais. A nova versão do Android tem as prin
"...dispositivos ativos do Android ultrapassa 2 bilhões mensais". Faz sentido esse "mensais" aqui? A príncipio essa expressão seria um sinônimo de "2 bilhões por mês", o que soa esquisito.

Acho que o início do segundo trecho poderia ser um pouco alterado:

"A nova versão do Android tem como principais características o foco em segurança..."

@tiagolimaelo7

2017-06-07 14:43 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Mirando no próximo bilhão usuários on-line para a plataforma está sendo desenvolvida a versão Android Go. Que tem como objetivo conseguir funcionar em celulares com poucos recursos e deverá ser lança
Incluir uma vírgula antes de "está sendo desenvolvida..." (oração subordinada explicativa)

O segundo trecho inicia com "Que tem como..." se referindo à oração anterior que na verdade já terminou. Faria sentido se fosse usada uma vírgula, mas acho melhor o "ponto na mesma linha como está", então sugiro mudar o "Que tem como objetivo..." para "Esse produto tem como objetivo...". Também poderia ser "Essa versão" mas aí essa palavra teria que sair da oração anterior:

"...está sendo desenvolvido o Android Go. Essa versão tem como objetivo..."

"conseguir funcionar" -> acho que apenas "funcionar" é melhor.

@tiagolimaelo7

2017-06-07 14:50 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Em 2016 a Google adquiriu a [Api.ai](https://api.ai) uma plataforma de conversação, que facilita a criação de bots, incluindo compreensão de linguagem natural em diversos idiomas, aprendizado de máqu
Incluir uma vírgula após "Em 2016" (adjunto adverbial de tempo iniciando frase)

Incluir uma vírgula após o "Api.ai" (antes de "uma plataforma de...", oração subordinada explicativa) e remover a vírgula após "conversação" (antes de "que facilita a criação...", conjunção subordinativa integrante).

Trocar a vírgula em "linguagem natural em diversos idiomas, aprendizado de máquina" por "e" ("linguagem natural em diversos idiomas e aprendizado de máquina").

Eu incluiria uma vírgula após "A plataforma evoluiu" apenas para melhorar a fluência do texto.

Onde diz "...um SDK bem evoluído..." talvez pudéssemos trocar a palavra "evoluído" aqui? É que ela foi usada imediatamente antes ("A plataforma evoluiu") e repetir palavras em um trecho próximo não é muito bom pra leitura 😄....talvez "um SDK bem maduro" seja melhor?

No final: "...que facilita a integração" ou "...para facilitar a integração"

@tiagolimaelo7

2017-06-07 14:52 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O foco no TensorFlow esta bastante elevado:
"está" com acento.

@tiagolimaelo7

2017-06-07 14:52 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +O suporte a novas linguagens de programação foi incorporado ao TensorFlow. Suportando agora Haskell, C++, Java, Python, Go, etc.
Vírgula ao invés de "ponto na mesma linha" ficaria melhor aqui, após "...ao TensorFlow"

@tiagolimaelo7

2017-06-07 14:56 UTC, tiagolimaelo7 commented on src/posts/google-io.html.md
> +Durante o evento foi anunciado o **TensorFlow Lite** uma versão do TensorFlow para mobile.
Incluir uma vírgula após o "TensorFlow Lite" (antes de "uma versão...", oração subordinada explicativa)

@tiagolimaelo7

2017-06-09 13:33 UTC, merged

2021-06-15 12:50 UTC, guruantree requested changes
@guruanthree